name: pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    name: Publish Time 2000 to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm set "//npm.pkg.github.com/:_authToken=$AUTH_TOKEN"
          npm install
          npm run build
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: dist
